import { APP_FEATURES } from '../../app-features';
import { INVENTORY_MANAGEMENT_SIDEBAR_CONFIG } from './inventory-management.config';
import { MEAL_DISTRIBUTION_SIDEBAR_CONFIG } from './meal-distribution.config';
import { MEAL_PLANNING_SIDEBAR_CONFIG } from './meal-planning.config';
import { MENU_MANAGEMENT_SIDEBAR_CONFIG } from './menu-management.config';
import { SCHOOL_MANAGEMENT_SIDEBAR_CONFIG } from './school-management.config';
import { USER_MANAGEMENT_SIDEBAR_CONFIG } from './user-management.config';

export {
  INVENTORY_MANAGEMENT_SIDEBAR_CONFIG,
  MEAL_DISTRIBUTION_SIDEBAR_CONFIG,
  MEAL_PLANNING_SIDEBAR_CONFIG,
  MENU_MANAGEMENT_SIDEBAR_CONFIG,
  SCHOOL_MANAGEMENT_SIDEBAR_CONFIG,
  USER_MANAGEMENT_SIDEBAR_CONFIG,
};

export const SIDEBAR_CONFIG_BY_FEATURE = Object.freeze({
  [APP_FEATURES.MEAL_DISTRIBUTION]: MEAL_DISTRIBUTION_SIDEBAR_CONFIG,
  [APP_FEATURES.SCHOOL_MANAGEMENT]: SCHOOL_MANAGEMENT_SIDEBAR_CONFIG,
  [APP_FEATURES.USER_MANAGEMENT]: USER_MANAGEMENT_SIDEBAR_CONFIG,
  [APP_FEATURES.INVENTORY_MANAGEMENT]: INVENTORY_MANAGEMENT_SIDEBAR_CONFIG,
  [APP_FEATURES.MEAL_PLANNING]: MEAL_PLANNING_SIDEBAR_CONFIG,
  [APP_FEATURES.MENU_MANAGEMENT]: MENU_MANAGEMENT_SIDEBAR_CONFIG,
});
